spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      additional-paths: src/main/resources
